# Generated by Django 2.2.9 on 2021-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviame', '0005_empresa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código'),
        ),
    ]
